### ISSUE TITLE
image has no reference

### ISSUE THREAD

**Issue by strudra** [JafarBadour/PI#1]
Image also found in:

- https://www.abc.net.au/triplej/programs/hack/cultural-bias-of-driverless-cars-determines-who-lives-and-dies/10425566
- http://theconversation.com/the-everyday-ethical-challenges-of-self-driving-cars-92710
- https://techcrunch.com/2016/10/04/did-you-save-the-cat-or-the-kid/
- https://www.popsci.com/consent.php?redirect=https%3a%2f%2fwww.popsci.com%2fmit-game-asks-who-driverless-cars-should-kill

Make a reference on where it is taken from.

**Comment by JafarBadour** [comment]
Resolved
